### ISSUE TITLE
Package runs into compile errors with GHC 

### ISSUE THREAD

**Issue by hvr** [myfreeweb/microformats2-parser#2]
See http://matrix.hackage.haskell.org/package/microformats2-parser

![tmp](https://cloud.githubusercontent.com/assets/285533/9428657/f57bd8b6-49b5-11e5-87ae-8d45fc8493fc.png)

From a first glance. this looks like the package is only compatible w/ `base == 4.8.*` but the bounds on `base` don't reflect this.

**Comment by myfreeweb** [comment]
Released 1.0.1 which should work on 7.8...

**Comment by hvr** [comment]
looks good; btw, I see you do almost exclusively minor-version bumps. It seems like you're following the semver convention (while Hackage follows the PVP)?

**Comment by myfreeweb** [comment]
Yes, I prefer semver.

I've read the PVP several times, and my understanding is that semver is compatible with PVP and stricter than PVP: PVP says `A.B` must be incremented when breaking backwards compatibility; semver says `A` must be incremented in that case.

**Comment by hvr** [comment]
Well, the problem is rather that you're confusing tooling as well as developers depending on your package. They'd put upper bounds expecting the PVP semantics of version bumps as is the established convention on Hackage. So while packages depending on your package assuming PVP-semantics won't break (i.e. run into compile errors), they will get stuck on older than necessary versions of your packages, because your version bumps signaled a potentially incompatible API change that didn't occur. 

With PVP-style minor version bumps this is less of a problem, but if you started doing minor-bumps according to the semver convention, they'd be viewed as major versions bumps according to the PVP.

I wish semver was known at the time the PVP was created, but it wasn't. In fact, the PVP predates semver by several years, so we're stuck with the PVP scheme for the foreseeable future.

**Comment by myfreeweb** [comment]
I believe users of my packages should use Stackage instead of version bounds ;-)

But yeah, sure, I'll do PVP-style minor bumps.

**Comment by mightybyte** [comment]
Hi, I thought I'd add a slightly different take on the semver thing.  I think of the PVP as essentially a superset of semver.  It's pretty much semver with another number added onto the front.  This gives developers a free axis they can use to communicate other things.  For instance, if you start a project with an 0.1 release.  Then you make a small change that breaks backwards compatibility, semver says you have to bump to 1.0.  Some people think of 1.0 as signaling that a project is "stable".  But even though this particular project might be far from it, you're forced to increment to that version.  I really like the PVP because it gives you discretionary control over the first number.  You might make a contract with your users that each individual A represents a long term supported release and that you'll always support the last N of them.

**Comment by myfreeweb** [comment]
Adding another number onto the front? Like `1.A.B.C` where `A.B.C` is semver? That's an excellent idea! Thank you!

**Comment by mightybyte** [comment]
I (and I think a fair number of other people tend to think of 0.x.y.z as being newer/less stable and 1.x.y.z as signalling some level of maturity / stability.  I think this is a good pattern to follow.

**Comment by myfreeweb** [comment]
Yeah – in semver, `0.y.z` means anything can change at any time, all semver conventions only apply to `1.y.z` and above.

**Comment by mightybyte** [comment]
Oh, I had missed that detail about semver.  In that case, that's another thing I don't like.  The PVP doesn't have that special casing of 0 because it doesn't need it thanks to the extra number.  This way the PVP does not sacrifice any of it's power to describe backwards compatibility when things are "unstable".
